### ISSUE TITLE
Incorrect formatting with nested arrays

### ISSUE THREAD

**Issue by wim07101993** [alexei-sintotski/pubspec_yaml#31]
When saving back to the `pubspec.yaml` i nocited that my fonts format wierd: 
```
  fonts:
    - family: 'larsseit'
      fonts:
        - asset: 'assets/fonts/larsseit/Larsseit-Bold.ttf'
        - asset: 'assets/fonts/larsseit/Larsseit-Medium.ttf'
    - family: 'roger_icons'
      fonts:
        - asset: 'assets/fonts/roger_icons/RogerIcons.ttf'
```
becomes:
```
  fonts:
    -
          family: larsseit
          fonts:
            -
                  asset: "assets/fonts/larsseit/Larsseit-Bold.ttf"
            -
                  asset: "assets/fonts/larsseit/Larsseit-Medium.ttf"
    -
          family: roger_icons
          fonts:
            -
                  asset: assets/fonts/roger_icons/RogerIcons.ttf

```
