### ISSUE TITLE
Support for new hosted dependencies format

### ISSUE THREAD

**Issue by greymag** [alexei-sintotski/pubspec_yaml#40]
Since Dart 2.15 we can define [hosted dependencies](https://dart.dev/tools/pub/dependencies#hosted-packages) like this:
```yaml
dependencies:
  transmogrify:
    hosted: https://some-package-server.com
    version: ^1.4.0
```

But trying to load such pubspec leads to exception:
```
type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
```
